spring:
  main:
    banner-mode: off
  h2.console:
    enabled: true
    path: '/console'
  jpa.hibernate:
    ddl-auto: create
  datasource:
    url: 'jdbc:h2:file:C:\\Users\\adamd\\IdeaProjects\\todoApp\\todo-db'
    username: test
    password: test
task.template.allowMultipleTasks: false